### ISSUE TITLE
Does it work with spring-boot?

### ISSUE THREAD

**Issue by ieugen** [tstout/spring-repl#5]
Hello,

Does it work with spring boot? Nice project. I was looking for something like this.

**Comment by tstout** [comment]
Should work fine. I have used it with spring boot services. If you find issues, let me know. I have updated the README to include some additional info.

**Comment by jiahut** [comment]
```
Exception in thread "main" java.lang.LinkageError: loader 'app' attempted duplicate class definition for org.springframework.boot.loader.jar.JarURLConnection$1. (org.springframework.boot.loader.jar.JarURLConnection$1 is in unnamed module of loader 'app')
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at org.springframework.boot.loader.jar.Handler.setUseFastConnectionExceptions(Handler.java:463)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:137)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

> java --version

java 17.0.3 2022-04-19 LTS
Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing

spring-boot 版本: 

``` pom.xml
        <spring-boot.version>2.7.18</spring-boot.version>
        <spring-starter.version>3.1.3</spring-starter.version>
```
